# Generated by Django 4.2.20 on 2025-04-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctions", "0002_alter_auction_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="auctioneer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_bids",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
