# Generated by Django 5.2 on 2025-05-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comment_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='rating',
        ),
    ]
