# Generated by Django 4.2.20 on 2025-04-10 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="municiaplity",
            new_name="municipality",
        ),
    ]
